index:
  path: /
  defaults: { _controller: App\Controller\IndexController::showIndex }

addEpreuve:
  path: /addEpreuve
  defaults: { _controller: App\Controller\EpreuveController::showEpreuve }

testParametre:
  path: /epreuve/{id}
  defaults: { _controller: App\Controller\EpreuveController::testParametre}