index:
  path: /
  defaults: { _controller: App\Controller\IndexController::showIndex }

addEpreuve:
  path: /epreuveList
  defaults: { _controller: App\Controller\EpreuveController::retrieveEpreuveList }

testParametre:
  path: /epreuve/{id}
  defaults: { _controller: App\Controller\EpreuveController::}
