index:
  path: /
  defaults: { _controller: App\Controller\IndexController::showIndex }

showEpreuve:
  path: /epreuveList
  defaults: { _controller: App\Controller\EpreuveController::retrieveEpreuveList }

showAddEpreuve:
  path: /addEpreuve
  defaults: { _controller: App\Controller\EpreuveController::showAddEpreuve }

deleteEpreuve:
  path: /deleteEpreuve/{id}
  defaults: { _controller: App\Controller\EpreuveController::deleteEpreuve }

addEpreuve:
  path: /addEpreuve/add
  defaults: { _controller: App\Controller\EpreuveController::addEpreuve }

testPersonne:
  path: /personneList
  defaults : { _controller: App\Controller\PersonneController::showPersonneList }
