index:
  path: /
  defaults: { _controller: App\Controller\IndexController::showIndex }

showEpreuveList:
  path: /epreuveList
  defaults: { _controller: App\Controller\EpreuveController::retrieveEpreuveList }

showAddEpreuve:
  path: /addEpreuve
  defaults: { _controller: App\Controller\EpreuveController::showAddEpreuve }

deleteEpreuve:
  path: /deleteEpreuve/{id}
  defaults: { _controller: App\Controller\EpreuveController::deleteEpreuve }

addEpreuve:
  path: /addEpreuve/add
  defaults: { _controller: App\Controller\EpreuveController::addEpreuve }

showEpreuve:
  path: /showEpreuve/{id}
  defaults: { _controller: App\Controller\EpreuveController::showSingleEpreuve }

updateEpreuve:
  path: /updateEpreuve/{id}
  defaults: { _controller: App\Controller\EpreuveController::updateEpreuve }

showAddPersonne:
  path: /{id}/addPersonne
  defaults: { _controller: App\Controller\PersonneController::showAddPersonne }

addPersonne:
  path: /{id}/addPersonne/add
  defaults: { _controller: App\Controller\PersonneController::addPersonne }